name: SonarQube Scan2.0
on: # Trigger analysis when finishing a pull request.
  pull_request:
    branch: "main"
    types: [closed]

jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
      - name: Install sonar-scanner
        run: npm install sonarqube-scanner
      - name: SonarQube Scan
        run: node ./sonarscan.js
